language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev
services:
- mysql

install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install git+https://github.com/PyCQA/flake8.git
- pip install coveralls
before_script:
- flake8 edc_pharmacy
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=edc_pharmacy manage.py test
after_success:
- coveralls
